package com.spop.poverlay.erg

/**
 * Feed-forward map of the Bike+ eddy brake: (cadence, target watts) -> resistance.
 *
 * GENERATED by power-sweep.py on 2026-08-18 from 23 samples across
 * 4 cadence bands. Do not hand-edit; re-run the sweep instead.
 *
 * Cells are resistance percentages. [NO_DATA] means the fit could not produce a
 * value for that cell, and [MEASURED] records whether a cell sits inside the
 * resistance range actually ridden, as opposed to extrapolated off the end of
 * the fitted curve.
 */
object PowerTableData {

    /** Flipped to true once a real sweep has replaced the placeholder values. */
    const val CALIBRATED = true

    val NO_DATA = Double.NaN

    const val CADENCE_BIN_BASE = 20
    const val CADENCE_BIN_STEP = 10
    const val CADENCE_BIN_COUNT = 9

    const val WATT_BIN_BASE = 25
    const val WATT_BIN_STEP = 25
    const val WATT_BIN_COUNT = 16

    /** [cadenceBin][wattBin] -> resistance percent. */
    val RESISTANCE: Array<DoubleArray> =
        arrayOf(
            // 20 rpm
            doubleArrayOf(48.86, 66.29, 79.15, 89.82, 99.15, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA),
            // 30 rpm
            doubleArrayOf(48.86, 66.29, 79.15, 89.82, 99.15, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA),
            // 40 rpm
            doubleArrayOf(40.61, 55.59, 66.49, 75.50, 83.36, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA),
            // 50 rpm
            doubleArrayOf(32.37, 44.90, 53.84, 61.19, 67.58, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA, NO_DATA),
            // 60 rpm
            doubleArrayOf(24.13, 34.20, 41.18, 46.87, 51.80, 56.20, 60.23, 63.95, 67.44, 70.72, 73.84, 76.81, 79.65, 82.39, 85.02, 87.57),
            // 70 rpm
            doubleArrayOf(NO_DATA, 30.61, 37.02, 42.13, 46.51, 50.42, 53.96, 57.24, 60.30, 63.18, 65.91, 68.52, 71.01, 73.40, 75.70, 77.92),
            // 80 rpm
            doubleArrayOf(NO_DATA, 27.03, 32.86, 37.39, 41.23, 44.63, 47.70, 50.53, 53.17, 55.65, 57.99, 60.23, 62.36, 64.41, 66.38, 68.28),
            // 90 rpm
            doubleArrayOf(NO_DATA, 23.73, 28.86, 32.89, 36.32, 39.37, 42.13, 44.67, 47.04, 49.28, 51.39, 53.40, 55.32, 57.17, 58.95, 60.66),
            // 100 rpm
            doubleArrayOf(NO_DATA, 23.73, 28.86, 32.89, 36.32, 39.37, 42.13, 44.67, 47.04, 49.28, 51.39, 53.40, 55.32, 57.17, 58.95, 60.66),
        )

    /** [cadenceBin][wattBin] -> true when interpolated rather than extrapolated. */
    val MEASURED: Array<BooleanArray> =
        arrayOf(
            // 20 rpm
            booleanArrayOf(false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false),
            // 30 rpm
            booleanArrayOf(true, true, false, false, false, false, false, false, false, false, false, false, false, false, false, false),
            // 40 rpm
            booleanArrayOf(false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false),
            // 50 rpm
            booleanArrayOf(false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false),
            // 60 rpm
            booleanArrayOf(true, true, true, true, true, true, true, true, true, false, false, false, false, false, false, false),
            // 70 rpm
            booleanArrayOf(false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false),
            // 80 rpm
            booleanArrayOf(false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, true),
            // 90 rpm
            booleanArrayOf(false, true, true, true, true, true, true, true, true, true, true, true, true, true, true, false),
            // 100 rpm
            booleanArrayOf(false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false),
        )
}
